on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - run: |
        docker login -u  ${{ github.repository_owner }} \
                     -p "${{ github.token }}" \
                         ghcr.io
        docker build -t  ghcr.io/${{ github.repository}}:${{ github.ref_name }} .
        
        docker push      ghcr.io/${{ github.repository}}:${{ github.ref_name }}
